GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5f06d1770fe1841a040b19af

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
   "name": "user3",
   "subscribedToChannel": "Web Dev Simplified"
}

###
PATCH http://localhost:3000/subscribers/5f06d17b0fe1841a040b19b0
Content-Type: application/json

{
   "name": "gouhar",
   "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/5f06cc43b2a4d71578bbb3cc

###
# Delete all subscribers
DELETE http://localhost:3000/subscribers